version: "3.8"
services:
  mongodb:
    image: mongo:4.2.0
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - $PWD/database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
